### ISSUE TITLE
Lambda parsing doesn't allow for no space between lambda and binder

### ISSUE THREAD

**Issue by solomon-b** [ToposInstitute/polytt#59]
It would be really helpful if this was a valid parse:

```
λx → .unit
```

**Comment by MonoidMusician** [comment]
I think I'd rather keep it as-is, so lambda can be used to start identifiers still (other than itself).

You can use `\` though

**Comment by solomon-b** [comment]
> I think I'd rather keep it as-is, so lambda can be used to start identifiers still (other than itself).
> 
> You can use `\` though

Okay. That makes sense.
